In [6]:
import pandas as pd
import os

In [2]:
pwd = '/sem_cluster/'

In [14]:
df_clusters = pd.DataFrame(columns=['identifier', 'cluster'])

In [18]:
for file in os.listdir(pwd):
    df = pd.read_csv(os.path.join(pwd, f'/clusters/{file}'), sep='\t')
    df_clusters = pd.concat([df_clusters, df])

In [22]:
df_clusters.reset_index(inplace=True)
df_clusters.drop(columns=['index'], inplace=True)

In [28]:
df_uses = pd.DataFrame()

In [30]:
for file in os.listdir(os.path.join(pwd, 'data')):
    try:
        df = pd.read_csv(os.path.join(pwd, f'data/{file}/uses.csv'), sep='\t')
        df_uses = pd.concat([df_uses, df])
    except:
        pass

In [33]:
df_uses

,lemma,pos,date,grouping,identifier,description,context,indexes_target_token,indexes_target_sentence,identifier_system,project,lang,user
0,жена,NN,example,22,22_жена_84953,NaN,"Высокая и плотная, Парасковья Ивановна сохрани...",89:92,0:119,28020,sem_cluster,ru,ek.gavrishina
1,жена,NN,example,22,22_жена_179,NaN,"В стране, где жена, любовница и просто женщина...",14:18,0:113,28011,sem_cluster,ru,ek.gavrishina
2,жена,NN,example,22,22_жена_76356,NaN,Потом останавливался перед наклеенной на стену...,139:143,0:319,28000,sem_cluster,ru,ek.gavrishina
3,жена,NN,example,22,22_жена_26928,NaN,"Только теперь догадался Коравье, что жене приш...",37:41,0:61,28016,sem_cluster,ru,ek.gavrishina
4,жена,NN,example,22,22_жена_59995,NaN,"Помните, лифтерша Марья Ивановна рассказывала,...",67:71,0:106,28014,sem_cluster,ru,ek.gavrishina
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,бог,NN,example,22,22_бог_63941,NaN,"-- Да знаю я, слава богу.",20:24,0:25,27739,sem_cluster,ru,ek.gavrishina
31,бог,NN,example,22,22_бог_7063,NaN,"Да и бог с ним, пусть у бестолкового творца хо...",5:8,0:118,27744,sem_cluster,ru,ek.gavrishina
32,бог,NN,example,22,22_бог_61740,NaN,-- Как бог еще терпит на свете такую пиявицу?,7:10,0:45,27745,sem_cluster,ru,ek.gavrishina
33,бог,NN,example,22,22_бог_16754,NaN,«Забыть?-- забвенья не дал бог: да он и не взя...,27:30,0:234,27720,sem_cluster,ru,ek.gavrishina
34,бог,NN,example,22,22_бог_284,NaN,"Боже, как мне было это дико слышать когда-то.",0:4,0:45,27747,sem_cluster,ru,ek.gavrishina

In [42]:
df_russe = pd.merge(df_uses[['identifier', 'context', 'indexes_target_token']], df_clusters, right_on='identifier', left_on='identifier')

In [45]:
df_russe.drop_duplicates(inplace=True)

In [46]:
df_russe['identifier'] = df_russe['identifier'].apply(lambda x: x.split('_')[1])

In [48]:
df_russe['indexes_target_token'] = df_russe['indexes_target_token'].apply(lambda x: x.replace(':', '-'))

In [50]:
df_russe.rename(columns={"identifier": "word", "cluster": "gold_sense_id", "indexes_target_token": "positions"}, inplace=True)

In [52]:
df_russe.reset_index(inplace=True)
df_russe.drop(columns=['index'], inplace=True)

In [53]:
df_russe['predict_sense_id'] = [''] * df_russe.shape[0]

In [57]:
df_russe.groupby('word')['gold_sense_id'].nunique()

word
бог             3
время          35
год            19
голова          6
город           3
государство    22
дело           12
день            8
жена            2
жизнь          10
лицо            4
место           7
мир             9
ночь            1
работа         10
результат      35
рука            3
сила           10
слово           7
сторона         8
тысяча         35
Name: gold_sense_id, dtype: int64